### ISSUE TITLE
Bugfixed Frogger mra

### ISSUE THREAD

**Issue by jstavats** [MiSTer-devel/Arcade-Scramble_MiSTer#17]
Hi,

I'm not sure how to contribute this but there is a patch to the konami frogger romfiles that fixes some bugs in frogger over at:

[http://www.ukvac.com/forum/frogger-bugs-descriptions-and-fixes_topic381374.html](url)

These issues appear to be present in the current mister sega rom set too. 

Anyways, I took the file from that forum and made up a .mra that applies the patch to the mame konami roms. I was hoping that somehow this could be added to the distro...

Perhaps this should go in the alternatives directory?

The file is submitted in the fork here:

https://github.com/jstavats/Arcade-Scramble_MiSTer/tree/patch-1

Jay

**Comment by sorgelig** [comment]
In your repository main page just above the list of files you can see the button "pull request" So press it and it will make PR to main repository.
About patches: You don't need to write address for every byte if they are sequential. Just set beginning address and then write array of bytes like: 00 00 00 00 
It will make a better look.

**Comment by jstavats** [comment]
Ok, thanks.  Submitted.  I knew about the multiple byte patching, but the original patch author presented only the bytes that he changed and many are non-consecutive (so I left it in his format rather than risk breaking it).

Jay

________________________________

**Comment by sorgelig** [comment]
submitted.
