### ISSUE TITLE
Color banding for VGA output in Vertical screen mode

### ISSUE THREAD

**Issue by eskwadrat** [MiSTer-devel/Arcade-Scramble_MiSTer#4]
Color banding on VGA output when switched to vertical screen mode when playing. Horizontal mode looks good. Confirmed on 3 different LCD monitors (Dell 20", Microtouch 15", Samsung 19") plus one CRT monitor (Viewsonic 17"). Per core developer feedback (Ash) it's most likely caused by bad timing (too short) for blanking signal (horizontal sync). That confuses the AGC circuits in most monitors, and causes that kind of banding. Similar issue observed for other arcade cores: burning rubber, catacomb, crazy kong, moon cresta, omega, pisces, pooyan, scramble, super glob.

**Comment by sorgelig** [comment]
stop spamming!

**Comment by eskwadrat** [comment]
Hi
I am not spamming. I am 50 year old arcade fan and happened to be embedded engineer for the living. I am very surprised with your response. I have spent significant amount of time to test MISTer prj arcade cores for my arcade machine I am building and found multiple issues that I am trying to
share for those developers who can help fixing it. Everything documented with a data pictures and spreadsheet log. And you are accusing me of spamming, how does that make me feel have you thought about it? You should be thankful for people like me that that take effort to test these cores that some of you are doing not insult me instead. I really hope you will come to your senses apologize and appreciate the effort I'm doing.

Let me know what are you take it from here.

Steve
eskwadrat

**Comment by sorgelig** [comment]
It would be enough to post in one arcade core and mention other arcades. It's not nice to come here and see tens of issues and realize it's the same issue.
It may look like exactly your monitor has this problem due to short blanking (i didn't check).
It's not exactly arcade is wrong. Arcades use special monitors with specialized schematics. That's why MiSTer's main output is HDMI where output is corrected and framed to look good.

**Comment by eskwadrat** [comment]
After Ash suggestion I am working to check timings for banding affected
cores. I worked around this issue by using monitors with DVI input, and it
solved the problem of course because I no longer use analog output. Not
every older 4:3 monitor has DVI though, so analog is still important for
some of users.

In general, not sure where to log the test results. After all core authors
may find results helpful to get core updated when they decide to do so. If
GitHub is not place for it then what is?

In the meantime, I will keep in mind your suggestion and refrain from
posting same issue on multiple repositories even if issue is common to
multiple cores.

I am not expecting relatively immature platform to perform perfect. However
I will make efforts to support development either via Patreon or engaging
into debugging myself when time permits.

Regards
Steve

**Comment by sorgelig** [comment]
If some issue appears common for many cores then it's better to report and talk about it in the forum.
Btw, your original term "Color banding" looks quite confusing and from my point of view is incorrect. Color banding is usually means lack of bits representing the color. For example system needs 8 bits per color component but VGA of MiSTer has only 6bits. Some cores supporting 24bit color may show color banding like Minimig where smooth color transition may show spotty transition instead. So it was strange to see "Color banding" issue on arcades where usually only 8-12 colors exist.

**Comment by eskwadrat** [comment]
Color banding is old term and it's origins come from times of analog tv. It
applies to what is observed in case of these 9 arcade cores and it has
little or nothing to do with number of bits.
You need to look at this from the monitor perspective and it's analog rgb
signal processing path. One of elements of this path is automatic gain
control circuit (AGC). Incorrect (too short) horizontal blanking (sync)
pulse causes AGC circuit to adjust line brightness incorrectly this results
line to be displayed darker. Multiple lines with incorrect blanking would
show as "band". That is exactly what is happening. Some old professional
monitors used in broadcast like popular today Sony PVM CRT series had
blanking processing circuit that was able to restore proper blanking length
thus AGC wasn't affected. Ash mentioned he used one of those monitors when
testing and developing the core so the issue was masked. However 99% of
monitors with analog input aren't that forgiving and these just follow the
timings of the blanking which results in the banding which is what I have
observed on four different monitors that I owe including LCD and CRT. So
there's nothing wrong with any of these monitors, what's wrong is the
signal is out of spec on analog output of the core.
Yes, it could be original arcade board inherent flaw as many of these
boards worked with open frame CRT monitors that has been very forgiving to
deviations of  analog video signal produced by the board.  In that case
fixing the problem may not be straightforward but at least we would know
and accept the root cause. It's something I'm going to investigate and stay
in touch with Ash to learn his findings. Adding simplelogic to restore
proper blanking with on the top of fpga core implementation is not a big
deal either. That should fix the problem.

Steve

**Comment by paulb-nl** [comment]
can be closed
